packages:
  - apps/*
  - packages/*

overrides:
  esbuild: 0.28.1
  postcss: 8.5.10

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
